### DISCUSSION TITLE
What scopes are required in the PAT?

### DISCUSSION THREAD

**Discussion by Pythonic-Rainbow** [DerLev/eslint-annotations#189] [Q&A] [answered]
Hi I am very sorry but I have given just about all the perms I can but I still can't get it work. It is probably my problem because I tried multiple ESLint annotation actions but It'd be nice if you can help me out. thank you in advance!

p.s. I am working on a private repo

![image](https://github.com/user-attachments/assets/b65589a1-fa95-4f64-a895-4339d5dae218)

I have the following in my workflow yml:
```yaml
jobs:
  build:
    permissions:
      # Default permissions (matching what would be set if the permissions section was missing at all)
      contents: write
      packages: read

      # Need to add these 2 for eslint-annotate-action
      pull-requests: read
      checks: write

    runs-on: ubuntu-latest

# ...

    - name: Annotate Code Linting Results
      uses: DerLev/eslint-annotations@v2
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        eslint-report: "eslint_report.json"
```

I pasted the entire token (github_pat_***) in my repo's `Settings > Security > Secrets and variables > Actions > ACCESS_TOKEN`

and the actions prints the following error ``Error: There has been an issue creating the status check. Does the action have the right permissions?``
